services:
  app:
    build:
      context: ./docker/php
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:KqLja9FZTzOYvDOshWESwiGZPqTQea7kURmtUSE73H8
    networks:
      - laravel_network

  webserver:
    image: nginx:stable
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - laravel_network

  mysql-db:
    image: mysql:8.0
    container_name: laravel-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel_network

volumes:
  db-data:

networks:
  laravel_network:
    driver: bridge